<template><div class="h-[calc(100vh-3.5rem)] overflow-y-auto p-4 space-y-4">
 <div class="flex items-center gap-3"><div><h1 class="text-base font-semibold text-gray-100">Central de Inteligência</h1><p class="text-[10px] text-gray-600">sinais · validação · divergências · saúde dos dados</p></div><div class="flex-1"/><form @submit.prevent="load" class="flex gap-2"><input v-model="symbol" class="form-input !py-1.5 text-xs w-32 uppercase"/><button class="btn-secondary !py-1.5 text-xs">Analisar</button></form></div>
 <div v-if="error" class="card p-3 text-red-400 text-xs">{{error}}</div>
 <template v-if="d&&!loading"><div class="grid grid-cols-2 md:grid-cols-5 gap-2">
  <div class="metric-card"><span class="metric-label">Sinal</span><span class="metric-value" :class="signalClass">{{d.signal.label}}</span></div>
  <div class="metric-card"><span class="metric-label">Score</span><span class="metric-value text-gray-100">{{d.signal.score.toFixed(2)}}</span></div>
  <div class="metric-card"><span class="metric-label">Confiança histórica</span><span class="metric-value text-accent-yellow">{{d.signal.confidence}}%</span><small class="text-[8px] text-gray-600">cobertura {{d.signal.coverage_pct??'—'}}%</small></div>
  <div class="metric-card"><span class="metric-label">Preço</span><span class="metric-value text-gray-100">{{money(d.signal.price)}}</span></div>
  <div class="metric-card"><span class="metric-label">Distância Pi Top</span><span class="metric-value text-gray-300">{{pct(d.liquidity?.pi_top_distance_pct)}}</span></div>
 </div>
 <div class="grid grid-cols-1 lg:grid-cols-2 gap-4"><div class="card p-4"><div class="title">Explicação do sinal</div><div v-for="r in d.signal.reasons" :key="r" class="text-xs text-gray-300 py-1 border-b border-surface-600">{{r}}</div></div>
 <div class="card p-4"><div class="title">Divergências</div><div v-for="x in d.divergences" :key="x.title" class="rounded bg-surface-600/30 p-2 mb-2"><div :class="x.severity==='warning'?'text-red-400':'text-green-400'" class="text-xs font-semibold">{{x.title}}</div><div class="text-[10px] text-gray-500">{{x.detail}}</div></div><p v-if="!d.divergences.length" class="text-xs text-gray-600">nenhuma divergência forte detectada</p></div></div>
 <div class="card p-4 overflow-x-auto"><div class="title">Validação histórica dos sinais</div><table class="w-full text-xs font-mono"><thead><tr class="text-gray-600"><th class="text-left">Sinal</th><th>Dias</th><th>Ret. 30d</th><th>Acerto 30d</th><th>Ret. 90d</th></tr></thead><tbody><tr v-for="(v,k) in d.validation" :key="k" class="border-t border-surface-600"><td class="py-2">{{k}}</td><td class="text-center">{{v.samples}}</td><td class="text-center">{{pct(v.return_30d_pct)}}</td><td class="text-center">{{pct(v.win_rate_30d_pct)}}</td><td class="text-center">{{pct(v.return_90d_pct)}}</td></tr></tbody></table></div>
 <div class="card p-4"><div class="title">Saúde das fontes</div><div v-for="h in d.health" :key="h.source" class="flex justify-between py-1 border-t border-surface-600 text-xs"><span class="text-gray-300">{{h.source}}</span><span :class="h.status==='ok'?'text-green-400':'text-amber-400'">{{h.status}} <small>{{h.detail}}</small></span></div></div>
 <div class="card p-4" v-if="liq"><div class="title">Liquidez e risco sistêmico · FRED</div><div class="grid grid-cols-2 md:grid-cols-3 gap-2"><div v-for="s in liq.series" :key="s.id" class="rounded bg-surface-600/30 p-2"><div class="text-[9px] text-gray-500 uppercase">{{s.label}}</div><div class="text-sm font-mono text-gray-200">{{s.value?.toLocaleString('pt-BR')??'—'}}</div><div class="text-[9px]" :class="(s.change_30??0)>=0?'text-green-500':'text-red-400'">Δ30 obs {{s.change_30?.toFixed(2)??s.status}}</div></div></div></div>
 </template></div></template>
<script setup>import{ref,computed,onMounted}from'vue';import{getIntelligence,getLiquidity}from'@/api/client.js';const symbol=ref('BTC'),d=ref(null),liq=ref(null),loading=ref(false),error=ref(null);const signalClass=computed(()=>d.value?.signal.label==='COMPRA'?'text-green-400':d.value?.signal.label==='VENDA'?'text-red-400':'text-gray-300');const pct=v=>v==null?'—':`${v>=0?'+':''}${Number(v).toFixed(2)}%`,money=v=>v==null?'—':`$${Number(v).toLocaleString('pt-BR',{maximumFractionDigits:2})}`;async function load(){loading.value=true;error.value=null;try{[d.value,liq.value]=await Promise.all([getIntelligence(symbol.value).then(r=>r.data),getLiquidity().then(r=>r.data)])}catch(e){error.value=e.response?.data?.error||e.message}finally{loading.value=false}}onMounted(load)</script>
<style scoped>.title{@apply text-[10px] text-gray-500 uppercase font-semibold mb-2}</style>
